### ISSUE TITLE
Add support for Contile test mode

### ISSUE THREAD

**Issue by ethowitz** [mozilla-services/contile-loadtests#8]
Let's add support for the test mode added to Contile in [#79](https://github.com/mozilla-services/contile/pull/79). We should add a number of possible `Fake-Response` headers:
- One that consists of corrupted data, causing Contile to return a 5XX error
- One that consists of valid tiles, causing Contile to return a 200 response
- One that consists of a valid response with no tiles, causing Contile to return a 204 response

This will require work on Contile to add the requisite test files.

**Comment by pjenvey** [comment]
Closing per https://github.com/mozilla-services/contile/issues/185
